### ISSUE TITLE
can JsonValue support std::string

### ISSUE THREAD

**Issue by qicosmos** [azadkuh/gason--#1]

**Comment by azadkuh** [comment]
`gason++` is mostly suitable for small embedded systems where _HEAP allocation_ is quite expensive or needs special consideration. the whole `STL` is around`new`/`delete` (HEAP allocations). so `std::string` / `std::list` / ... are not top priority in such libraries.

> `gason++` **reuse** the parsed memory an it's very RAM friendly. it means that the original json data won't be copied at parsing and the memory allocations will be reused for next parsings.

by the way using std::string is quite easy and it's highly recommended if you like STL, thanks to std::string's `ctor`s and `operator=()` overloads.

``` cpp
// gason++ & std::string
std::string message = root["a_message"].toString(&ok);
```

please keep in mind that `std::string message` makes a _copy_ from the original data.
