### ISSUE TITLE
Can we have gson++ next release ? Now.

### ISSUE THREAD

**Issue by DBJDBJ** [azadkuh/gason--#7]
2019 Q4 -- and everyone is back paddling out of exceptions. (and out of std::string too)

[Here is the latest WG21 results of the costs of using exceptions.](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1640r1.html)

Can we have gson++ back from the dead ? :)

**Comment by azadkuh** [comment]
@DBJDBJ thank you for the link, but this was a `json` parser for a **µcontroller** with a very old and non-conformant `c++98` toolkit, and as i remember without supporting `stl`, `new/delete`, `exception`, ...

**Comment by DBJDBJ** [comment]
I am using jzon from https://github.com/vivkin .... currently, see no problems.
